CREATE TABLE "guide" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "guide_type" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "recommend" TEXT NOT NULL,
    "comments" TEXT,
    "date_modified" TIMESTAMPTZ DEFAULT now() NOT NULL
);